### ISSUE TITLE
The user voice links are now http again

### ISSUE THREAD

**Issue by ghost** [MicrosoftEdge/Status#154] opened 2014-11-13 02:52 UTC
The user voice links were updated to use https (#142). Why are they now back to http? Please fix it.
https://status.modern.ie/uservoice

**Comment by jacobrossi** [comment] 2014-11-13 03:16
Tagging in @molant too. Perhaps the Azure WebJob that updates UV data is stomping on #142 ?  Let me know if I did something wrong that regressed this. :-)

**Comment by molant** [comment] 2014-11-13 16:34
Swapping slots in Azure Websites probably swaps too the WebJobs and the staging one was using the old code. I'll fix it now

**Comment by molant** [comment] 2014-11-13 16:38
I'm checking the current links and they are https.
I think the issue is that there is a period of time when we push changes that it is using an old version of the json that contains http links instead of https but once we pull the new info the links are ok.
I'll update the current file in the master branch to use https so this doesn't happen again.

**Comment by ghost** [comment] 2014-12-04 09:28
@molant Unfortunately, this happens again. Now they are all http. See https://status.modern.ie/uservoice.

**Comment by molant** [comment] 2014-12-04 16:27
Things that could be happening:
1. goblins change the code
2. code for the webjob gets swapped too when changing slots in Azure Website

my bet is #1 but I'll take a look to #2...

Thanks!

**Comment by jacobrossi** [comment] 2014-12-04 17:03
I've root caused this to:
1. cosmic interference.

😉 

-----Original Message-----

**Comment by molant** [comment] 2015-01-06 05:01
Closed via #170

**Closed as completed by molant** 2015-01-06 05:01 UTC

**Comment by ghost** [comment] 2015-08-21 12:47
The uservoice link is http again. E.g. https://dev.modern.ie/platform/status/adownloadattribute/. @jacobrossi @molant
