### ISSUE TITLE
Search broken on status.microsoftedge.com

### ISSUE THREAD

**Issue by mohamedmansour** [MicrosoftEdge/Status#672] opened 2020-04-20 16:53 UTC
Search bar is broken on "Microsoft Edge Platform".
 https://developer.microsoft.com/en-us/microsoft-edge/status/​​​​​​​

**Comment by molant** [comment] 2020-04-20 20:07
Ping @ststimac

**Comment by ststimac** [comment] 2020-04-20 20:21
Yes, I'm aware of this and need to file a bug.

**Comment by ststimac** [comment] 2020-04-20 20:35
I've filed a bug with the appropriate people and will update when I can. All filtering/search on that page seems to be broken/not affecting the page.

**Comment by olgamarti** [comment] 2020-04-30 22:56
The problem is fixed in production. @ststimac can you verify it and close the issue? Thanks!

**Comment by ststimac** [comment] 2020-05-04 15:49
This is all fixed. Thank you @olgamarti!

**Closed as completed by ststimac** 2020-05-04 15:49 UTC
