### ISSUE TITLE
UserVoice link votes

### ISSUE THREAD

**Issue by benaadams** [MicrosoftEdge/Status#207] opened 2015-04-02 20:23 UTC
Uservoice link displays number of comments not number of votes

**Comment by molant** [comment] 2015-04-02 20:26
That's weird, it didn't do that before :/

**Comment by molant** [comment] 2015-04-02 20:37
So the problem is that the job to get the latest data stopped working and we were using the info we have in this repo. This should be fixed now

**Closed as completed by molant** 2015-04-02 20:37 UTC
